trigger: none

pool: dev-infra-pool
stages: 
- stage: Build
  displayName: Terraform_install

  jobs:
    - job: build
      displayName: Terraform_init
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

- stage: Terraform_init
  jobs:
    - job: initjob
      steps: 
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
          backendServiceArm: 'infra-service-connection'
          backendAzureRmStorageAccountName: 'backendstg02'
          backendAzureRmContainerName: 'strg'
          backendAzureRmKey: 'terraform.tfstate'
