trigger:
  branches:
    include:
    - main
    # exclude:
    # - feature: 


pool: dev-infra-pool
stages: 
- stage: Build
  displayName: Terraform_install

  jobs:
    - job: build
      displayName: Terraform_init
      pool: dev-infra-pool
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

- stage: Terraform_init
  jobs:
    - job: initjob
      displayName: Terraforminit
      steps: 
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
          backendServiceArm: 'infra-service-connection'
          backendAzureRmStorageAccountName: 'backendstg02'
          backendAzureRmContainerName: 'strg'
          backendAzureRmKey: 'terraform.tfstate'


- stage: Manual_validation
  jobs:
    - job: Manualvalidation
      displayName: manualvalidation
      pool: server
      steps: 
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'shashisingh223344@gmail.com'
          approvers: 'shashisingh223344@gmail.com'
          instructions: 'please approve'
