trigger: none

pool: dev-infra-pool
jobs:
  - job: build
    displayName: Terraform_init
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendServiceArm: 'infra-service-connection'
        backendAzureRmStorageAccountName: 'backendstg02'
        backendAzureRmContainerName: 'strg'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        environmentServiceNameAzureRM: 'infra-service-connection'
